# Generated by Django 6.0 on 2026-09-15 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Начат'), ('finished', 'Закончен')], default='started', max_length=20, verbose_name='Статус')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_module_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прохождение урока',
                'verbose_name_plural': 'Прохождение урока',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserModulProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Начат'), ('finished', 'Закончен'), ('waiting', 'Не начат')], default='waiting', max_length=20, verbose_name='Статус')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modul_progress', to='courses.module', verbose_name='Модуль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс модулей',
                'verbose_name_plural': 'Прогресс модулей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Начат'), ('finished', 'Закончен')], default='started', max_length=20, verbose_name='Статус')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('current_class', models.IntegerField(default=1, verbose_name='Текущий урок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progres_us', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к курсам',
                'verbose_name_plural': 'Доступ к курсам',
                'ordering': ['-created_at'],
            },
        ),
    ]
