# Generated by Django 6.0 on 2026-09-28 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('progress', '0002_progres_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-created_at'], 'verbose_name': 'Прогрес курса ', 'verbose_name_plural': 'Прогрес курса'},
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Начат'), ('finished', 'Закончен'), ('waiting', 'Не начат')], default='waiting', max_length=20, verbose_name='Статус')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='courses.module', verbose_name='Модуль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс модулей',
                'verbose_name_plural': 'Прогресс модулей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserModulProgress',
        ),
        migrations.AddConstraint(
            model_name='usermoduleprogress',
            constraint=models.UniqueConstraint(fields=('user', 'module'), name='unique_user_module_progress'),
        ),
    ]
