--
-- PostgreSQL database dump
--

\restrict 9VADbsG0V74BVbN8q6LHT1SMGKOarG3FpGG6U56uWUX6OIx3RZFy5gmYtqoa4CE

-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    is_superuser boolean NOT NULL,
    phon_number character varying(64) NOT NULL
);


--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_userdocuments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_userdocuments (
    id bigint NOT NULL,
    diploma character varying(100) NOT NULL,
    passport_main character varying(100) NOT NULL,
    passport_registration character varying(100) NOT NULL,
    snils character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: accounts_userdocuments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_userdocuments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_userdocuments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_usertests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_usertests (
    id bigint NOT NULL,
    test_results character varying(100) NOT NULL,
    status character varying NOT NULL,
    lesson_id bigint NOT NULL,
    user_id bigint NOT NULL,
    rejection_reason character varying,
    course_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: accounts_usertests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_usertests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_usertests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_course; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses_course (
    id bigint NOT NULL,
    title character varying NOT NULL,
    short_description text NOT NULL,
    description text NOT NULL,
    lenth character varying(64) NOT NULL,
    price numeric(10,2) NOT NULL,
    output jsonb,
    image character varying(100)
);


--
-- Name: courses_course_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_coursemodule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses_coursemodule (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    course_id bigint NOT NULL,
    module_id bigint NOT NULL,
    CONSTRAINT courses_coursemodule_order_check CHECK (("order" >= 0))
);


--
-- Name: courses_coursemodule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses_coursemodule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_coursemodule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_lesson; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses_lesson (
    id bigint NOT NULL,
    title character varying(500) NOT NULL,
    video character varying(100),
    text_info text,
    test character varying(500),
    description text,
    has_video boolean NOT NULL
);


--
-- Name: courses_lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses_lesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_lessonmaterials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses_lessonmaterials (
    id bigint NOT NULL,
    material_type character varying(10) NOT NULL,
    necessity character varying(20) NOT NULL,
    link character varying(200),
    file character varying(100),
    "order" integer NOT NULL,
    title character varying(150) NOT NULL,
    lesson_id bigint NOT NULL,
    CONSTRAINT courses_lessonmaterials_order_c8f2e56c_check CHECK (("order" >= 0))
);


--
-- Name: courses_lessonmaterials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses_lessonmaterials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_lessonmaterials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_module; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses_module (
    id bigint NOT NULL,
    title character varying NOT NULL,
    description text NOT NULL
);


--
-- Name: courses_module_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses_module ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_module_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_modulelesson; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses_modulelesson (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    lesson_id bigint NOT NULL,
    module_id bigint NOT NULL,
    CONSTRAINT courses_modulelesson_order_check CHECK (("order" >= 0))
);


--
-- Name: courses_modulelesson_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses_modulelesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_modulelesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: main_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.main_documents (
    id bigint NOT NULL,
    title character varying NOT NULL,
    link character varying NOT NULL,
    status character varying NOT NULL
);


--
-- Name: main_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.main_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_userpayments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_userpayments (
    id uuid NOT NULL,
    status character varying(20) NOT NULL,
    amount numeric(10,2) NOT NULL,
    provider_payment_id character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: progress_userlessonprogress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.progress_userlessonprogress (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lesson_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: progress_userlessonprogress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.progress_userlessonprogress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progress_userlessonprogress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: progress_usermodulprogress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.progress_usermodulprogress (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    finished_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    modul_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: progress_usermodulprogress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.progress_usermodulprogress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progress_usermodulprogress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: progress_userprogress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.progress_userprogress (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    finished_at timestamp with time zone,
    current_class integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: progress_userprogress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.progress_userprogress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progress_userprogress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.accounts_user (id, password, last_login, username, first_name, last_name, email, date_joined, is_staff, is_active, is_superuser, phon_number) FROM stdin;
1	pbkdf2_sha256$1200000$g9jAZ1r9fnndVslITq5vHc$vI/Mg64taxeIG+6D/xrFZE9Jo7OKrTXQQbqmbgeYrAM=	2026-09-15 19:16:01+03	root			test@mail.ru	2026-09-13 17:57:58+03	t	t	t	+79999999999
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
1	1	1
2	1	2
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: accounts_userdocuments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.accounts_userdocuments (id, diploma, passport_main, passport_registration, snils, status, comment, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: accounts_usertests; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.accounts_usertests (id, test_results, status, lesson_id, user_id, rejection_reason, course_id, created_at) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
1	admin
2	can_buy_courses
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add пользователя	6	add_user
22	Can change пользователя	6	change_user
23	Can delete пользователя	6	delete_user
24	Can view пользователя	6	view_user
25	Can add Документы пользователя	7	add_userdocuments
26	Can change Документы пользователя	7	change_userdocuments
27	Can delete Документы пользователя	7	delete_userdocuments
28	Can view Документы пользователя	7	view_userdocuments
29	Can add Тест пользователя	8	add_usertests
30	Can change Тест пользователя	8	change_usertests
31	Can delete Тест пользователя	8	delete_usertests
32	Can view Тест пользователя	8	view_usertests
33	Can add Урок	11	add_lesson
34	Can change Урок	11	change_lesson
35	Can delete Урок	11	delete_lesson
36	Can view Урок	11	view_lesson
37	Can add Материал	12	add_lessonmaterials
38	Can change Материал	12	change_lessonmaterials
39	Can delete Материал	12	delete_lessonmaterials
40	Can view Материал	12	view_lessonmaterials
41	Can add Модуль	13	add_module
42	Can change Модуль	13	change_module
43	Can delete Модуль	13	delete_module
44	Can view Модуль	13	view_module
45	Can add Курс	9	add_course
46	Can change Курс	9	change_course
47	Can delete Курс	9	delete_course
48	Can view Курс	9	view_course
49	Can add Модули	10	add_coursemodule
50	Can change Модули	10	change_coursemodule
51	Can delete Модули	10	delete_coursemodule
52	Can view Модули	10	view_coursemodule
53	Can add Уроки	14	add_modulelesson
54	Can change Уроки	14	change_modulelesson
55	Can delete Уроки	14	delete_modulelesson
56	Can view Уроки	14	view_modulelesson
57	Can add Документы	15	add_documents
58	Can change Документы	15	change_documents
59	Can delete Документы	15	delete_documents
60	Can view Документы	15	view_documents
61	Can add Доступ к курсам	18	add_userprogress
62	Can change Доступ к курсам	18	change_userprogress
63	Can delete Доступ к курсам	18	delete_userprogress
64	Can view Доступ к курсам	18	view_userprogress
65	Can add Прохождение урока	16	add_userlessonprogress
66	Can change Прохождение урока	16	change_userlessonprogress
67	Can delete Прохождение урока	16	delete_userlessonprogress
68	Can view Прохождение урока	16	view_userlessonprogress
69	Can add Прогресс модулей	17	add_usermodulprogress
70	Can change Прогресс модулей	17	change_usermodulprogress
71	Can delete Прогресс модулей	17	delete_usermodulprogress
72	Can view Прогресс модулей	17	view_usermodulprogress
73	Can add Платёж пользователя	19	add_userpayments
74	Can change Платёж пользователя	19	change_userpayments
75	Can delete Платёж пользователя	19	delete_userpayments
76	Can view Платёж пользователя	19	view_userpayments
\.


--
-- Data for Name: courses_course; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.courses_course (id, title, short_description, description, lenth, price, output, image) FROM stdin;
1	Введение в профессию	Курс познакомит вас с профессией психолога, основными направлениями психологии, принципами работы специалиста и базовыми профессиональными навыками.	Курс «Введение в профессию психолога» — это первый шаг к знакомству с психологией как профессиональной сферой. Вы узнаете, чем занимается психолог, какие существуют направления и подходы в современной психологии, как строится работа с клиентом и какие профессиональные и этические принципы должен соблюдать специалист.\r\n\r\nВ рамках курса вы познакомитесь с основами профессиональной деятельности психолога, особенностями взаимодействия с клиентом, принципами психологического консультирования и требованиями к профессиональной компетентности специалиста.\r\n\r\nКурс поможет сформировать целостное представление о профессии, понять её особенности и определить дальнейшее направление своего профессионального развития.	40	18900.00	["Знания о том, как устроена профессия", "уроки, учебные материалы и тесты с проверкой", "диплом об окончании курса"]	materials/course_images/professiya-psiholog-1232.jpg
\.


--
-- Data for Name: courses_coursemodule; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.courses_coursemodule (id, "order", course_id, module_id) FROM stdin;
1	1	1	1
2	2	1	2
3	3	1	4
4	4	1	3
\.


--
-- Data for Name: courses_lesson; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.courses_lesson (id, title, video, text_info, test, description, has_video) FROM stdin;
2	Профессия психолога: задачи и особенности работы		Профессия психолога сегодня востребована в самых разных сферах — от индивидуального консультирования и образования до бизнеса, медицины, спорта и научных исследований. Однако представление о психологе как о специалисте, который просто «выслушивает людей и даёт советы», является слишком упрощённым.\r\n\r\nПрофессиональная деятельность психолога значительно шире. Специалист работает с психологическими особенностями человека, его эмоциональным состоянием, поведением, отношениями и жизненными трудностями. В зависимости от направления деятельности психолог может проводить диагностику, консультирование, развивающую и коррекционную работу, заниматься профилактикой, исследованиями или обучением.\r\n\r\nПри этом работа психолога требует не только знаний о психике человека, но и развитых профессиональных навыков. Важную роль играют умение устанавливать контакт, внимательно слушать, правильно задавать вопросы, анализировать полученную информацию и соблюдать профессиональную этику.\r\n\r\nВ этом уроке мы разберём, чем на самом деле занимается психолог, какие задачи входят в его профессиональную деятельность и в каких сферах может работать специалист. Это поможет сформировать более точное представление о профессии и понять, какие знания и компетенции необходимы для её освоения.	\N	Что представляет собой профессия психолога, чем занимается специалист и какие задачи решает в своей работе. Вы познакомитесь с основными направлениями профессиональной деятельности и ролью психолога в работе с человеком.	f
1	История и причины появления психологии	materials/lessons_video/Kooha-2026-09-13-20-23-13.webm	Психология как самостоятельная наука появилась сравнительно недавно, однако интерес к психике и внутреннему миру человека существует уже тысячи лет. Ещё в древности философы пытались понять природу сознания, мышления, эмоций и поведения человека.\r\n\r\nДолгое время вопросы, которые сегодня относятся к психологии, рассматривались преимущественно в рамках философии, религии и медицины. Постепенно развитие научного знания изменило подход к изучению человека. Наблюдение, эксперимент и новые представления о работе организма позволили перейти от рассуждений о психике к её систематическому научному исследованию.\r\n\r\nОсобенно важным стал XIX век, когда появились условия для формирования психологии как отдельной научной дисциплины. Возникновение первых лабораторий и психологических школ положило начало новому этапу изучения человеческой психики.\r\n\r\nВ этом уроке мы проследим основные этапы становления психологии, рассмотрим причины её появления и узнаем, какие идеи и научные достижения способствовали превращению размышлений о психике в самостоятельную область науки.	http://127.0.0.1:8000/	Психология изучает психику, поведение и взаимодействие человека с окружающим миром. Однако интерес к внутреннему миру человека возник задолго до появления психологии как науки.\r\n\r\nВ этом уроке мы рассмотрим, как развивались представления о психике и почему в XIX веке психология стала самостоятельной научной дисциплиной.	t
\.


--
-- Data for Name: courses_lessonmaterials; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.courses_lessonmaterials (id, material_type, necessity, link, file, "order", title, lesson_id) FROM stdin;
1	file	necessary	\N	materials/files/professiya-psiholog-1232.jpg	1	История психологии	1
2	link	recommended	http://127.0.0.1:8000/		1	Цели психологии	1
3	file	necessary	\N	materials/files/professiya-psiholog-1232_iaIqqTR.jpg	1	Правила психолога	2
4	link	recommended	http://127.0.0.1:8000		1	Опыт психологического консультирования	2
\.


--
-- Data for Name: courses_module; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.courses_module (id, title, description) FROM stdin;
4	Строение психики	Психика представляет собой сложную систему взаимосвязанных процессов и компонентов. Вы узнаете, из чего состоит психика человека, как взаимодействуют её основные элементы и какое значение они имеют для поведения и деятельности.
2	Профессиональная деятельность	Модуль посвящён изучению основных компонентов психики человека. Вы узнаете о психических процессах, состояниях и свойствах личности, их взаимосвязи и влиянии на поведение и деятельность человека.
3	Основы психологического консультирования	Психологическое консультирование — важная часть работы психолога с клиентом. Вы узнаете, как строится консультативный процесс, какие этапы он включает и какую роль играют доверие, активное слушание и профессиональная позиция специалиста.
1	История и причины появления психологии	От первых философских размышлений до научных исследований — путь психологии занял тысячи лет. Вы узнаете, как формировались представления о психике и какие идеи и открытия привели к появлению психологии как самостоятельной науки.
\.


--
-- Data for Name: courses_modulelesson; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.courses_modulelesson (id, "order", lesson_id, module_id) FROM stdin;
2	1	2	2
1	1	1	1
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	accounts	userdocuments
8	accounts	usertests
9	courses	course
10	courses	coursemodule
11	courses	lesson
12	courses	lessonmaterials
13	courses	module
14	courses	modulelesson
15	main	documents
16	progress	userlessonprogress
17	progress	usermodulprogress
18	progress	userprogress
19	payment	userpayments
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	courses	0001_initial	2026-08-10 17:30:05.728647+03
2	courses	0002_alter_lesson_text_info	2026-08-10 17:30:05.755622+03
3	courses	0003_lesson_title1_lesson_title2_lesson_title3_and_more	2026-08-10 17:30:05.775879+03
4	courses	0004_lesson_rec_title1_lesson_rec_title2_and_more	2026-08-10 17:30:05.793448+03
5	courses	0005_lesson_description	2026-08-10 17:30:05.810573+03
6	courses	0006_alter_lesson_must_file1_alter_lesson_must_file2_and_more	2026-08-10 17:30:05.842135+03
7	courses	0007_lessonmaterials_remove_lesson_must_file1_and_more	2026-08-10 17:30:06.115437+03
8	courses	0008_remove_lesson_material_lessonmaterials_lesson	2026-08-10 17:30:06.304796+03
9	courses	0009_alter_lessonmaterials_options_lessonmaterials_order_and_more	2026-08-10 17:30:06.362123+03
10	courses	0010_alter_lessonmaterials_necessity	2026-08-10 17:30:06.390459+03
11	courses	0011_alter_lessonmaterials_order	2026-08-10 17:30:06.452335+03
12	contenttypes	0001_initial	2026-08-10 17:30:06.551301+03
13	contenttypes	0002_remove_content_type_name	2026-08-10 17:30:06.577965+03
14	auth	0001_initial	2026-08-10 17:30:06.961605+03
15	auth	0002_alter_permission_name_max_length	2026-08-10 17:30:06.97994+03
16	auth	0003_alter_user_email_max_length	2026-08-10 17:30:07.000023+03
17	auth	0004_alter_user_username_opts	2026-08-10 17:30:07.00901+03
18	auth	0005_alter_user_last_login_null	2026-08-10 17:30:07.021471+03
19	auth	0006_require_contenttypes_0002	2026-08-10 17:30:07.028016+03
20	auth	0007_alter_validators_add_error_messages	2026-08-10 17:30:07.045811+03
21	auth	0008_alter_user_username_max_length	2026-08-10 17:30:07.054675+03
22	auth	0009_alter_user_last_name_max_length	2026-08-10 17:30:07.066374+03
23	auth	0010_alter_group_name_max_length	2026-08-10 17:30:07.077364+03
24	auth	0011_update_proxy_permissions	2026-08-10 17:30:07.096138+03
25	auth	0012_alter_user_first_name_max_length	2026-08-10 17:30:07.111902+03
26	accounts	0001_initial	2026-08-10 17:30:07.818469+03
27	accounts	0002_usertests	2026-08-10 17:30:08.029802+03
28	accounts	0003_alter_usertests_status	2026-08-10 17:30:08.054906+03
29	accounts	0004_usertests_rejection_reason_alter_usertests_status	2026-08-10 17:30:08.077908+03
30	accounts	0005_alter_usertests_options	2026-08-10 17:30:08.089869+03
31	accounts	0006_alter_userdocuments_user	2026-08-10 17:30:08.146694+03
32	accounts	0007_alter_userdocuments_user_alter_usertests_user	2026-08-10 17:30:08.293518+03
33	accounts	0008_alter_usertests_lesson	2026-08-10 17:30:08.372096+03
34	accounts	0009_rename_fon_number_user_phon_number	2026-08-10 17:30:08.398954+03
35	accounts	0010_alter_userdocuments_diploma_and_more	2026-08-10 17:30:08.427097+03
36	accounts	0011_userpayments	2026-08-10 17:30:08.685902+03
37	accounts	0012_alter_userpayments_options_alter_userpayments_amount_and_more	2026-08-10 17:30:09.080656+03
38	admin	0001_initial	2026-08-10 17:30:09.275701+03
39	admin	0002_logentry_remove_auto_add	2026-08-10 17:30:09.295113+03
40	admin	0003_logentry_add_action_flag_choices	2026-08-10 17:30:09.305938+03
41	courses	0012_alter_course_price	2026-08-10 17:30:09.412761+03
42	courses	0013_alter_lessonmaterials_options_alter_course_output_and_more	2026-08-10 17:30:09.453148+03
43	main	0001_initial	2026-08-10 17:30:09.59128+03
44	main	0002_alter_documents_options_alter_documents_title	2026-08-10 17:30:09.615531+03
45	main	0003_alter_documents_link	2026-08-10 17:30:09.704704+03
46	main	0004_rename_link_documents_file	2026-08-10 17:30:09.724866+03
47	main	0005_remove_documents_file_documents_link	2026-08-10 17:30:09.737566+03
48	progress	0001_initial	2026-08-10 17:30:09.922279+03
49	progress	0002_alter_userprogress_finished_at	2026-08-10 17:30:09.948726+03
50	progress	0003_alter_userprogress_course	2026-08-10 17:30:10.052017+03
51	progress	0004_alter_userprogress_user_userlessonprogress_and_more	2026-08-10 17:30:10.433941+03
52	progress	0005_rename_module_userlessonprogress_lesson_and_more	2026-08-10 17:30:10.481289+03
53	progress	0006_alter_userlessonprogress_user_and_more	2026-08-10 17:30:10.778604+03
54	progress	0007_alter_usermodulprogress_modul	2026-08-10 17:30:10.810371+03
55	progress	0008_alter_usermodulprogress_status	2026-08-10 17:30:10.84262+03
56	progress	0009_alter_userlessonprogress_options_and_more	2026-08-10 17:30:10.872556+03
57	progress	0010_alter_userlessonprogress_lesson	2026-08-10 17:30:10.896423+03
58	sessions	0001_initial	2026-08-10 17:30:11.067809+03
59	courses	0014_alter_course_options_alter_course_description_and_more	2026-08-10 20:05:06.502344+03
60	main	0006_documents_status	2026-08-10 21:29:33.459198+03
61	accounts	0013_alter_userdocuments_diploma_and_more	2026-08-31 11:07:47.062868+03
62	courses	0015_alter_lesson_video_alter_lessonmaterials_file	2026-08-31 11:07:47.218378+03
64	accounts	0014_alter_user_email	2026-08-31 17:06:13.791522+03
65	courses	0016_lesson_has_video	2026-09-02 08:18:18.345526+03
66	payment	0001_initial	2026-09-06 11:16:24.547929+03
67	courses	0017_course_image	2026-09-06 13:21:05.577154+03
68	accounts	0015_alter_usertests_lesson	2026-09-10 19:03:28.139881+03
69	accounts	0016_usertests_course	2026-09-10 19:26:36.347021+03
70	accounts	0017_usertests_created_at	2026-09-12 10:09:37.970825+03
71	accounts	0018_alter_usertests_created_at	2026-09-12 10:09:47.050235+03
72	courses	0018_alter_course_short_description_and_more	2026-09-13 21:33:33.647669+03
73	courses	0002_remove_module_course_remove_module_output_and_more	2026-09-15 17:51:23.900682+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: main_documents; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.main_documents (id, title, link, status) FROM stdin;
\.


--
-- Data for Name: payment_userpayments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.payment_userpayments (id, status, amount, provider_payment_id, created_at, updated_at, course_id, user_id) FROM stdin;
\.


--
-- Data for Name: progress_userlessonprogress; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.progress_userlessonprogress (id, status, finished_at, created_at, updated_at, lesson_id, user_id) FROM stdin;
\.


--
-- Data for Name: progress_usermodulprogress; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.progress_usermodulprogress (id, status, finished_at, created_at, updated_at, modul_id, user_id) FROM stdin;
\.


--
-- Data for Name: progress_userprogress; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.progress_userprogress (id, status, finished_at, current_class, created_at, updated_at, course_id, user_id) FROM stdin;
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 2, true);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 1, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: accounts_userdocuments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_userdocuments_id_seq', 1, false);


--
-- Name: accounts_usertests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.accounts_usertests_id_seq', 2, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


--
-- Name: courses_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_course_id_seq', 1, true);


--
-- Name: courses_coursemodule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_coursemodule_id_seq', 4, true);


--
-- Name: courses_lesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_lesson_id_seq', 2, true);


--
-- Name: courses_lessonmaterials_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_lessonmaterials_id_seq', 4, true);


--
-- Name: courses_module_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_module_id_seq', 4, true);


--
-- Name: courses_modulelesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_modulelesson_id_seq', 2, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 69, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 73, true);


--
-- Name: main_documents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.main_documents_id_seq', 1, false);


--
-- Name: progress_userlessonprogress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.progress_userlessonprogress_id_seq', 3, true);


--
-- Name: progress_usermodulprogress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.progress_usermodulprogress_id_seq', 12, true);


--
-- Name: progress_userprogress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.progress_userprogress_id_seq', 3, true);


--
-- Name: accounts_user accounts_user_email_b2644a56_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_b2644a56_uniq UNIQUE (email);


--
-- Name: accounts_user accounts_user_fon_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_fon_number_key UNIQUE (phon_number);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: accounts_userdocuments accounts_userdocuments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_userdocuments
    ADD CONSTRAINT accounts_userdocuments_pkey PRIMARY KEY (id);


--
-- Name: accounts_userdocuments accounts_userdocuments_user_id_4d8e1310_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_userdocuments
    ADD CONSTRAINT accounts_userdocuments_user_id_4d8e1310_uniq UNIQUE (user_id);


--
-- Name: accounts_usertests accounts_usertests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usertests
    ADD CONSTRAINT accounts_usertests_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: courses_course courses_course_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT courses_course_pkey PRIMARY KEY (id);


--
-- Name: courses_coursemodule courses_coursemodule_course_id_module_id_e8bf7026_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_coursemodule
    ADD CONSTRAINT courses_coursemodule_course_id_module_id_e8bf7026_uniq UNIQUE (course_id, module_id);


--
-- Name: courses_coursemodule courses_coursemodule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_coursemodule
    ADD CONSTRAINT courses_coursemodule_pkey PRIMARY KEY (id);


--
-- Name: courses_lesson courses_lesson_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_lesson
    ADD CONSTRAINT courses_lesson_pkey PRIMARY KEY (id);


--
-- Name: courses_lessonmaterials courses_lessonmaterials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_lessonmaterials
    ADD CONSTRAINT courses_lessonmaterials_pkey PRIMARY KEY (id);


--
-- Name: courses_module courses_module_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_module
    ADD CONSTRAINT courses_module_pkey PRIMARY KEY (id);


--
-- Name: courses_modulelesson courses_modulelesson_module_id_lesson_id_54903d4c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_modulelesson
    ADD CONSTRAINT courses_modulelesson_module_id_lesson_id_54903d4c_uniq UNIQUE (module_id, lesson_id);


--
-- Name: courses_modulelesson courses_modulelesson_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_modulelesson
    ADD CONSTRAINT courses_modulelesson_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: main_documents main_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.main_documents
    ADD CONSTRAINT main_documents_pkey PRIMARY KEY (id);


--
-- Name: payment_userpayments payment_userpayments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_userpayments
    ADD CONSTRAINT payment_userpayments_pkey PRIMARY KEY (id);


--
-- Name: payment_userpayments payment_userpayments_provider_payment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_userpayments
    ADD CONSTRAINT payment_userpayments_provider_payment_id_key UNIQUE (provider_payment_id);


--
-- Name: progress_userlessonprogress progress_userlessonprogress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_userlessonprogress
    ADD CONSTRAINT progress_userlessonprogress_pkey PRIMARY KEY (id);


--
-- Name: progress_usermodulprogress progress_usermodulprogress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_usermodulprogress
    ADD CONSTRAINT progress_usermodulprogress_pkey PRIMARY KEY (id);


--
-- Name: progress_userprogress progress_userprogress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_userprogress
    ADD CONSTRAINT progress_userprogress_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_fon_number_16624f86_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_fon_number_16624f86_like ON public.accounts_user USING btree (phon_number varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: accounts_usertests_course_id_5fef5f8c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usertests_course_id_5fef5f8c ON public.accounts_usertests USING btree (course_id);


--
-- Name: accounts_usertests_lesson_id_72962b0e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usertests_lesson_id_72962b0e ON public.accounts_usertests USING btree (lesson_id);


--
-- Name: accounts_usertests_user_id_c02837ff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_usertests_user_id_c02837ff ON public.accounts_usertests USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: courses_coursemodule_course_id_805095bb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX courses_coursemodule_course_id_805095bb ON public.courses_coursemodule USING btree (course_id);


--
-- Name: courses_coursemodule_module_id_5bf62ab2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX courses_coursemodule_module_id_5bf62ab2 ON public.courses_coursemodule USING btree (module_id);


--
-- Name: courses_lessonmaterials_lesson_id_2016cf84; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX courses_lessonmaterials_lesson_id_2016cf84 ON public.courses_lessonmaterials USING btree (lesson_id);


--
-- Name: courses_modulelesson_lesson_id_e43a782c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX courses_modulelesson_lesson_id_e43a782c ON public.courses_modulelesson USING btree (lesson_id);


--
-- Name: courses_modulelesson_module_id_768ce73b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX courses_modulelesson_module_id_768ce73b ON public.courses_modulelesson USING btree (module_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: payment_userpayments_course_id_d6397276; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payment_userpayments_course_id_d6397276 ON public.payment_userpayments USING btree (course_id);


--
-- Name: payment_userpayments_provider_payment_id_ac2c4d22_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payment_userpayments_provider_payment_id_ac2c4d22_like ON public.payment_userpayments USING btree (provider_payment_id varchar_pattern_ops);


--
-- Name: payment_userpayments_user_id_b1846c5c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payment_userpayments_user_id_b1846c5c ON public.payment_userpayments USING btree (user_id);


--
-- Name: progress_userlessonprogress_module_id_f8783aa4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_userlessonprogress_module_id_f8783aa4 ON public.progress_userlessonprogress USING btree (lesson_id);


--
-- Name: progress_userlessonprogress_user_id_40575672; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_userlessonprogress_user_id_40575672 ON public.progress_userlessonprogress USING btree (user_id);


--
-- Name: progress_usermodulprogress_lesson_id_2bb6ad10; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_usermodulprogress_lesson_id_2bb6ad10 ON public.progress_usermodulprogress USING btree (modul_id);


--
-- Name: progress_usermodulprogress_user_id_cd28566c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_usermodulprogress_user_id_cd28566c ON public.progress_usermodulprogress USING btree (user_id);


--
-- Name: progress_userprogress_course_id_657a3320; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_userprogress_course_id_657a3320 ON public.progress_userprogress USING btree (course_id);


--
-- Name: progress_userprogress_user_id_fec1b33d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_userprogress_user_id_fec1b33d ON public.progress_userprogress USING btree (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_userdocuments accounts_userdocuments_user_id_4d8e1310_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_userdocuments
    ADD CONSTRAINT accounts_userdocuments_user_id_4d8e1310_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_usertests accounts_usertests_course_id_5fef5f8c_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usertests
    ADD CONSTRAINT accounts_usertests_course_id_5fef5f8c_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_usertests accounts_usertests_lesson_id_72962b0e_fk_courses_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usertests
    ADD CONSTRAINT accounts_usertests_lesson_id_72962b0e_fk_courses_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.courses_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_usertests accounts_usertests_user_id_c02837ff_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_usertests
    ADD CONSTRAINT accounts_usertests_user_id_c02837ff_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_coursemodule courses_coursemodule_course_id_805095bb_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_coursemodule
    ADD CONSTRAINT courses_coursemodule_course_id_805095bb_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_coursemodule courses_coursemodule_module_id_5bf62ab2_fk_courses_module_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_coursemodule
    ADD CONSTRAINT courses_coursemodule_module_id_5bf62ab2_fk_courses_module_id FOREIGN KEY (module_id) REFERENCES public.courses_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_lessonmaterials courses_lessonmaterials_lesson_id_2016cf84_fk_courses_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_lessonmaterials
    ADD CONSTRAINT courses_lessonmaterials_lesson_id_2016cf84_fk_courses_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.courses_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_modulelesson courses_modulelesson_lesson_id_e43a782c_fk_courses_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_modulelesson
    ADD CONSTRAINT courses_modulelesson_lesson_id_e43a782c_fk_courses_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.courses_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_modulelesson courses_modulelesson_module_id_768ce73b_fk_courses_module_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_modulelesson
    ADD CONSTRAINT courses_modulelesson_module_id_768ce73b_fk_courses_module_id FOREIGN KEY (module_id) REFERENCES public.courses_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payment_userpayments payment_userpayments_course_id_d6397276_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_userpayments
    ADD CONSTRAINT payment_userpayments_course_id_d6397276_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payment_userpayments payment_userpayments_user_id_b1846c5c_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_userpayments
    ADD CONSTRAINT payment_userpayments_user_id_b1846c5c_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: progress_userlessonprogress progress_userlessonp_lesson_id_1d49ef70_fk_courses_l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_userlessonprogress
    ADD CONSTRAINT progress_userlessonp_lesson_id_1d49ef70_fk_courses_l FOREIGN KEY (lesson_id) REFERENCES public.courses_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: progress_userlessonprogress progress_userlessonp_user_id_40575672_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_userlessonprogress
    ADD CONSTRAINT progress_userlessonp_user_id_40575672_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: progress_usermodulprogress progress_usermodulpr_modul_id_2d17c0b3_fk_courses_m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_usermodulprogress
    ADD CONSTRAINT progress_usermodulpr_modul_id_2d17c0b3_fk_courses_m FOREIGN KEY (modul_id) REFERENCES public.courses_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: progress_usermodulprogress progress_usermodulprogress_user_id_cd28566c_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_usermodulprogress
    ADD CONSTRAINT progress_usermodulprogress_user_id_cd28566c_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: progress_userprogress progress_userprogress_course_id_657a3320_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_userprogress
    ADD CONSTRAINT progress_userprogress_course_id_657a3320_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: progress_userprogress progress_userprogress_user_id_fec1b33d_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_userprogress
    ADD CONSTRAINT progress_userprogress_user_id_fec1b33d_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 9VADbsG0V74BVbN8q6LHT1SMGKOarG3FpGG6U56uWUX6OIx3RZFy5gmYtqoa4CE

