# Generated by Django 6.0 on 2026-09-15 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('canceled', 'Отменён'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('access_granted', 'Доступ предоставлен'), ('creation_error', 'Ошибка создания платежа'), ('verify_error', 'Ошибка верификации платежа')], default='processing', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID платежа в платёжной системе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёж пользователя',
                'verbose_name_plural': 'Платежи пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
