# Generated by Django 6.0 on 2026-09-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertests',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тест пользователя', 'verbose_name_plural': 'Тесты пользователей'},
        ),
    ]
