# Generated by Django 6.0 on 2026-09-30 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_modul_to_module'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phon_number',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='usertests',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='rejection_reason',
            field=models.CharField(blank=True, default=12, verbose_name='Причина отказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertests',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('succeeded', 'succeeded'), ('processing', 'processing')], default='processing', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usertests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
