# Generated by Django 6.0 on 2026-09-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(verbose_name='Ссылка на документ')),
                ('title', models.CharField(verbose_name='Название документа')),
                ('status', models.CharField(choices=[('structure', 'Структура'), ('local', 'Локальные')], default='local', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
