# Generated by Django 6.0 on 2026-09-15 15:50

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/course_images', verbose_name='Баннер')),
                ('short_description', models.TextField(max_length=400, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('lenth', models.CharField(max_length=64, verbose_name='Продолжительность курса')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('output', models.JSONField(blank=True, null=True, verbose_name='Что вы получите')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('video', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/mint1/Desktop/Code/Psychology/private_media')), upload_to='materials/lessons_video', verbose_name='Видеоурок')),
                ('has_video', models.BooleanField(default=False, verbose_name='Наличие видео')),
                ('text_info', models.TextField(blank=True, null=True, verbose_name='Введение')),
                ('test', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на тест')),
                ('description', models.TextField(blank=True, max_length=330, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.CreateModel(
            name='LessonMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('link', 'Ссылка'), ('file', 'Файл')], max_length=10, verbose_name='Тип материала')),
                ('necessity', models.CharField(choices=[('necessary', 'Обязательный'), ('recommended', 'Дополнительный')], max_length=20, verbose_name='Обязательность')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/mint1/Desktop/Code/Psychology/private_media')), upload_to='materials/files', verbose_name='Файл')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson', verbose_name='Уроки')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='courses.course', verbose_name='Курс')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Модули',
                'verbose_name_plural': 'Модули',
                'ordering': ['order'],
                'unique_together': {('course', 'module')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(related_name='courses', through='courses.CourseModule', to='courses.module', verbose_name='Модули'),
        ),
        migrations.CreateModel(
            name='ModuleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_lessons', to='courses.module')),
            ],
            options={
                'verbose_name': 'Уроки',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
                'unique_together': {('module', 'lesson')},
            },
        ),
        migrations.AddField(
            model_name='module',
            name='lessons',
            field=models.ManyToManyField(related_name='modules', through='courses.ModuleLesson', to='courses.lesson'),
        ),
    ]
